### ISSUE TITLE
python3.6 tensorflow 1.13.1 can't run directly 需要修改代码才能跑

### ISSUE THREAD

**Issue by whtlook** [bonlime/keras-deeplab-v3-plus#92]
I'm a beginner. I downloaded this code and I found that it can't run directly.
I'm using tensorflow 1.13.1 with keras 2.2.4，and pycharm.
First I find ' import from tensorflow.keras.models import Model ' is not right.
It should be ' **from keras.models import Model** '.So I change all 'tensorflow.keras' to ' keras 'to get rid of the red wavy lines.
And don't forget to **add ' from tensorflow.python.keras.applications import imagenet_utils '**. It is used in 'preprocess_input', although it is defined without usage.

Second, **in the function '_inverted_res_block'** , around line 191,  **expansion * in_channels** needs to be changed to **int(expansion * in_channels)**. Otherwise you will get TypeError: float() argument must be a string or a number, not 'Dimension'. It is because the type of the 'in_channels' is <class 'tensorflow.python.framework.tensor_shape.Dimension'>,not int.

if block_id:
       # Expand
       x = Conv2D(**int**(expansion * in_channels), kernel_size=1, padding='same',
                   use_bias=False, activation=None,
                   name=prefix + 'expand')(x)

Third, in the function ' Deeplabv3 ', around line 381, after  **b4 = GlobalAveragePooling2D()(x), a direct usage of ' b4 = tf.expand_dims(tf.expand_dims(b4, 1), 1) ' is not correct**. It will give you 'AttributeError: 'NoneType' object has no attribute '_inbound_nodes'.  It will return a Tensor, not a Layer so it doesn't have a attribute 'inbount_nodes'.
I solve this problem by changing it to:

**def expand_dims(xxx):
        return tf.expand_dims(tf.expand_dims(xxx, 1), 1)
b4 = Lambda(expand_dims)(b4)**
and that's all. I could  run it successfully.

**Comment by sachsbl** [comment]
I'm trying to start a project that provides more of a Quickstart to running this model.  It should run with a simple pip install and no other modifications.  It provides a CLI and a Dockerized method to run it.  It uses TF 2.0 Alpha and Python 3.7.  You can check it out here:
https://github.com/sachsbl/segmental

**Comment by whtlook** [comment]
Around line 450
x = Lambda(lambda xx: tf.compat.v1.image.resize(xx, tf.shape(img_input)[1:3],
                                                    **method='bilinear'**, align_corners=True))(x)
change it to **method=0**, or just delete it.

**Comment by bonlime** [comment]
@whtlook in you've read README more carefully you would've noticed there is an older commit which works with TF 1.13 and Keras 2.2.4 and you could simply use `git checkout 714a6b7d1a069a07547c5c08282f1a706db92e20` instead of fixing all these things manually
